defaults:
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_sft_dreamzero_full_8gpu"
    logger_backends: ["tensorboard", "wandb"]

  max_epochs: 100000
  max_steps: 50000
  val_check_interval: -1
  save_interval: 2000
  log_interval: 10

data:
  train_data_paths: ${oc.env:LIBERO_DATA_PATH,/mnt/project_rlinf_hs/yuanhuining/datasets/libero}

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1
  global_batch_size: 4
  seed: 42
  dataloader_num_workers: 4

  model:
    model_type: "dreamzero"
    precision: bf16
    model_path: ${oc.env:DREAMZERO_MODEL_PATH,/mnt/project_rlinf/hf_models/DreamZero-AgiBot}
    tokenizer_path: ${oc.env:UMT5_TOKENIZER_PATH,google/umt5-xxl}
    max_seq_len: 512
    # DreamZero-LIBERO: action_horizon=16, num_chunks=4 => 64 actions, frame_seqlen=512
    dreamzero_action_horizon: 16
    dreamzero_num_chunks: 4
    dreamzero_max_action_dim: 32
    dreamzero_max_state_dim: 64
    action_dim: 7
    embodiment_tag: "libero_sim"
    cpu_init: true
    cfg_mode: false
    advantage_parquet: ${oc.env:CFG_ADVANTAGE_PARQUET,advantages_test.parquet}
    unconditional_prob: ${oc.env:CFG_UNCONDITIONAL_PROB,0.3}
    add_value_head: false
    is_lora: true

  optim:
    lr: 1.0e-5
    value_lr: 1.55e-4
    adam_beta1: 0.95
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    weight_decay: 1.0e-5
    clip_grad: 1.0
    lr_scheduler: "cosine"
    lr_warmup_steps: 2500
    total_training_steps: 50000

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "full_shard"
    use_orig_params: true
    gradient_checkpointing: true
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: false

critic:
  use_critic_model: false
